// <auto-generated />
using System;
using Flota.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flota.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20251221170801_Start")]
    partial class Start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flota.Domain.Entities.Kierowca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerPrawaJazdy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Kierowcy");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Pojazd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerRejestracyjny")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PojemnoscZbiornika")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Przebieg")
                        .HasColumnType("decimal(12,1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("NumerRejestracyjny")
                        .IsUnique();

                    b.ToTable("Pojazdy");

                    b.HasDiscriminator<string>("Typ").HasValue("Pojazd");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Flota.Domain.Entities.Tankowanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaZaLitr")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IloscLitrow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PojazdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PojazdId");

                    b.ToTable("Tankowania");
                });

            modelBuilder.Entity("Flota.Domain.Entities.SamochodCiezarowy", b =>
                {
                    b.HasBaseType("Flota.Domain.Entities.Pojazd");

                    b.Property<decimal>("Ladownosc")
                        .HasColumnType("decimal(10,2)");

                    b.HasDiscriminator().HasValue("Ciezarowy");
                });

            modelBuilder.Entity("Flota.Domain.Entities.SamochodOsobowy", b =>
                {
                    b.HasBaseType("Flota.Domain.Entities.Pojazd");

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Osobowy");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Tankowanie", b =>
                {
                    b.HasOne("Flota.Domain.Entities.Pojazd", "Pojazd")
                        .WithMany("Tankowania")
                        .HasForeignKey("PojazdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pojazd");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Pojazd", b =>
                {
                    b.Navigation("Tankowania");
                });
#pragma warning restore 612, 618
        }
    }
}
