// <auto-generated />
using System;
using Flota.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flota.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260119172101_DodanieUbezpieczen")]
    partial class DodanieUbezpieczen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.1.25081.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flota.Domain.Entities.Kierowca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LataDoswiadczenia")
                        .HasColumnType("int");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrTelefonu")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NumerPrawaJazdy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NumerPrawaJazdy")
                        .IsUnique();

                    b.ToTable("Kierowcy");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Pojazd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumerRejestracyjny")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PojemnoscZbiornika")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Przebieg")
                        .HasColumnType("decimal(12,1)");

                    b.Property<int>("RokProdukcji")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumerRejestracyjny")
                        .IsUnique();

                    b.ToTable("Pojazdy");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Przydzial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("KierowcaId")
                        .HasColumnType("int");

                    b.Property<int>("PojazdId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrzebiegKoncowy")
                        .HasColumnType("decimal(12,1)");

                    b.Property<decimal>("PrzebiegPoczatkowy")
                        .HasColumnType("decimal(12,1)");

                    b.HasKey("Id");

                    b.HasIndex("KierowcaId");

                    b.HasIndex("PojazdId");

                    b.ToTable("Przydzialy");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Tankowanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaZaLitr")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IloscLitrow")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PojazdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PojazdId");

                    b.ToTable("Tankowania");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Ubezpieczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Koszt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumerPolisy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PojazdId")
                        .HasColumnType("int");

                    b.Property<string>("Ubezpieczyciel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PojazdId");

                    b.ToTable("Ubezpieczenia");
                });

            modelBuilder.Entity("Flota.Domain.Entities.WpisSerwisowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZgloszenia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Koszt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PojazdId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PojazdId");

                    b.ToTable("ZgloszeniaSerwisowe");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Przydzial", b =>
                {
                    b.HasOne("Flota.Domain.Entities.Kierowca", "Kierowca")
                        .WithMany()
                        .HasForeignKey("KierowcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flota.Domain.Entities.Pojazd", "Pojazd")
                        .WithMany("Przydzialy")
                        .HasForeignKey("PojazdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowca");

                    b.Navigation("Pojazd");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Tankowanie", b =>
                {
                    b.HasOne("Flota.Domain.Entities.Pojazd", "Pojazd")
                        .WithMany("Tankowania")
                        .HasForeignKey("PojazdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pojazd");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Ubezpieczenie", b =>
                {
                    b.HasOne("Flota.Domain.Entities.Pojazd", "Pojazd")
                        .WithMany("Ubezpieczenie")
                        .HasForeignKey("PojazdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pojazd");
                });

            modelBuilder.Entity("Flota.Domain.Entities.WpisSerwisowy", b =>
                {
                    b.HasOne("Flota.Domain.Entities.Pojazd", "Pojazd")
                        .WithMany("ZgloszeniaSerwisowe")
                        .HasForeignKey("PojazdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pojazd");
                });

            modelBuilder.Entity("Flota.Domain.Entities.Pojazd", b =>
                {
                    b.Navigation("Przydzialy");

                    b.Navigation("Tankowania");

                    b.Navigation("Ubezpieczenie");

                    b.Navigation("ZgloszeniaSerwisowe");
                });
#pragma warning restore 612, 618
        }
    }
}
